
RX_DATA_TYPE_CELL_TESTER_STATUS = 0
RX_DATA_TYPE_LOGGING_DATA = 1

SAMSUMG_30Q_MIN_V = 2.5
MIN_CURRENT_START_IR_CALULATIONS_A = 8

CELL_OC_CURRENT_MIN_A = 0.100
ZERO_VOLTAGE_THRESHOLD_V = 0.02
ZERO_VOLTAGE_NO_CELL_THRESHOLD_V = 0.5
ZERO_CURRENT_THRESHOLD_A = 0.15
ZERO_TEMPERATURE_THRESHOLD_C = 1

NUM_SAMPLES_IN_OPEN_CIRCUIT_AVERAGE = 10
NUM_SAMPLES_IN_CURRENT_AVERAGE = 10

OHMS_TO_MILLIOHMS = 1000

LOG_DIR = "../../../2024_CellData/"
