VOLTAGE_OC_CURRENT_LIMIT = 0.100

RX_DATA_TYPE_CELL_TESTER_STATUS = 0
RX_DATA_TYPE_LOGGING_DATA = 1

SAMSUMG_30Q_MIN_VOLTAGE = 2.5

ZERO_VOLTAGE_THRESHOLD = 0.02
ZERO_CURRENT_THRESHOLD = 0.1
ZERO_TEMPERATURE_THRESHOLD = 1

NUM_SAMPLES_IN_OPEN_CIRCUIT_AVERAGE = 10
NUM_SAMPLES_IN_CURRENT_AVERAGE = 10

OHMS_TO_MILLIOHMS = 1000

LOG_DIR = "../../../2024_CellData/"
