#ifndef CAN_RECEIVE_H_
#define CAN_RECEIVE_H_

#include "bsp.h"
#define WIRELESS_CAN_FLOAT_SCALAR 0.001f

extern uint32_t lastChargeCartHeartbeat;

typedef enum {
    BMU_CAN_CONFIGURED_MAX_CHARGE_CURRENT = 0U,
    BMU_CAN_CONFIGURED_SERIES_CELL_IR,
    BMU_CAN_CONFIGURED_STATE_BUS_HV_SEND_PERIOD,
    BMU_CAN_CONFIGURED_CAPACITY_STARTUP,
    BMU_CAN_CONFIGURED_IBUS_INTEGRATED,

    BMU_CAN_CONFIGURED_COUNT,
} BMU_CAN_CONFIGURED_E;

#endif /* USER_CAN_H_ */
