#ifndef PRECHARGEDISCHARGE_H

#define PRECHARGEDISCHARGE_H

#include "main.h"
#include "FreeRTOS.h"
#include "bsp.h"

typedef enum PCDC_Notifications_t {
    PRECHARGE_NOTIFICATION_MOTOR_CONTROLLERS,
    PRECHARGE_NOTIFICATION_CHARGER,
    DISCHARGE_NOTIFICATION,
    STOP_NOTIFICATION,
} PCDC_Notifications_t;

/*
 * Discharge constants
 */

#define DISCHARGE_MEASURE_PERIOD_MS 100
#define DISCHARGE_DONE_BUS_VOLTAGE (0.2F)

#define ZERO_CURRENT_MAX_AMPS (0.1)
#define CONTACTOR_OPEN_ZERO_CURRENT_TIMEOUT_MS 50

/*
 * Precharge constants
 */

#define PRECHARGE_RESISTOR_OHMS (10000)

// Timeouts
#define PRECHARGE_STEP_1_WAIT_TIME_MS 2000

#define PRECHARGE_STEP_2_WAIT_TIME_MS 2000
#define PRECHARGE_STEP_2_TIMEOUT 5000

#define PRECHARGE_STEP_3_WAIT_TIME_MS 2000

#define PRECHARGE_STEP_4_CURRENT_MEASURE_PERIOD_MS (1)
#define PRECHARGE_STEP_4_TIMEOUT 60000

#define PRECHARGE_STEP_5_CURRENT_MEASURE_PERIOD_MS (1)
#define PRECHARGE_STEP_5_TIMEOUT 60000

// Constants

#define VPACK (20.0F)
#define PACK_VOLTAGE_TOLERANCE_PERCENT (0.1)

#define PRECHARGE_STEP_1_VBUS_MAX_PERCENT_VPACK (0.85F)
#define PRECHARGE_STEP_1_VBATT_MAX_PERCENT_VPACK (0.05F)
#define PRECHARGE_STEP_1_CURRENT_MAX (1.500F)

#define PRECHARGE_STEP_2_VBUS_MAX_PERCENT_VPACK (0.15F)
#define PRECHARGE_STEP_2_PERCENT_VBATT_MAX (0.15)
#define PRECHARGE_STEP_2_CURRENT_MAX (1.50F)

#define PRECHARGE_STEP_3_VBUS_MIN_PERCENT_VPACK (0.85F)
#define PRECHARGE_STEP_3_VBATT_MAX_PERCENT_VPACK (0.15F)
#define PRECHARGE_STEP_3_CURRENT_MAX (1.5F)

#define PRECHARGE_STEP_4_AVERAGE (250)
#define PRECHARGE_STEP_4_DIFF_TOLERANCE (1.0F)
#define PRECHARGE_STEP_4_COMPLETE_PERCENT_VPACK (0.90F)
#define MIN_PRECHARGE_PERCENT_IDEAL_CURRENT (0.6F)

#define PRECHARGE_STEP_5_COMPLETE_PERCENT_VPACK (0.98F)
#define PRECHARGE_STEP_5_PERCENT_IDEAL_CURRENT_REQUIRED (0.8F)

#endif /* end of include guard: PRECHARGEDISCHARGE_H */
