#ifndef CAN_RECEIVE_H_
#define CAN_RECEIVE_H_

#include "stdbool.h"
#include "bsp.h"

#define WIRELESS_CAN_FLOAT_SCALAR 0.001f

bool getHvEnableState();
bool getMotorControllersStatus();
uint32_t lastBrakeValReceiveTimeTicks;
typedef enum {
    VCU_CAN_CONFIGURED_INITIAL_SOC = 0U,
    VCU_CAN_CONFIGURED_NUM_LAPS,
    VCU_CAN_CONFIGURED_NUM_LAPS_TO_COMPLETE,
    VCU_CAN_CONFIGURED_IN_ENDURANCE_MODE,
    VCU_CAN_CONFIGURED_EM_KP,
    VCU_CAN_CONFIGURED_EM_KI,
    VCU_CAN_CONFIGURED_TC_ON,
    VCU_CAN_CONFIGURED_TC_KP,
    VCU_CAN_CONFIGURED_TC_ERROR_FLOOR_RAD_S,
    VCU_CAN_CONFIGURED_TC_MIN_PERCENT_ERROR,
    VCU_CAN_CONFIGURED_TC_TORQUE_MAX_FLOOR,
    VCU_CAN_CONFIGURED_TV_DEAD_ZONE_END_RIGHT,
    VCU_CAN_CONFIGURED_TV_DEAD_ZONE_END_LEFT,
    VCU_CAN_CONFIGURED_TORQUE_VECTOR_FACTOR,
    VCU_CAN_CONFIGURED_MAX_TORQUE_DEMAND,

    VCU_CAN_CONFIGURED_COUNT,
} VCU_CAN_CONFIGURED_E;

#endif /* USER_CAN_H_ */
