BINARY_BASE_NAME=DCU
BOARD_NAME=DCU

COMMON_LIB_SRC = userCan.c debug.c CRC_CALC.c
COMMON_F0_LIB_SRC = userCanF0.c

# one of NUCLEO_F7, F7, NUCLEO_F0, F0
BOARD_TYPE=NUCLEO_F0

CUBE_F0_MAKEFILE_PATH= Cube-F0-Src/
CUBE_NUCLEO_F0_MAKEFILE_PATH = Cube-Nucleo-Src/DCU/


include common-all/tail-f7.mk
