#ifndef DIGITAL_POT_H
#define DIGITAL_POT_H
 
 // Potentiometer part number: AD5260BRUZ200-RL7
#define WIPER_RESISTANCE_OHM 60
#define MAX_POT_DIGITAL_VALUE 256
#define NOMINAL_RESISTANCE_OHM 200000
#define LSB_OHM (((NOMINAL_RESISTANCE_OHM)/MAX_POT_DIGITAL_VALUE)+WIPER_RESISTANCE_OHM) //841 OHM
#define POT_MAX_OHM (NOMINAL_RESISTANCE_OHM-LSB_OHM+WIPER_RESISTANCE_OHM) //199,219 OHM

#define PDU_MSG_STATUS_CAN_ID 0x8020F03
#define EXTENDED_MSG 1
#define POT_CAN_MSG_DATA_SIZE 1 //size in bytes

void setPotResistance (uint32_t resistance);

#endif/*DIGITAL_POT_H*/
