#ifndef HIL_CAN_H
#define HIL_CAN_H

/*
 * Hand-written stand-in for the DBC-autogenerated "<board>_can.h" that every
 * vehicle board gets from common/Scripts/generateCANHeadder.py.
 *
 * HIL is not a node in common/Data/2024CAR.dbc and is not part of the
 * DBC/DTC codegen pipeline (see ../README.md) - there is no Gen/HIL/
 * directory. This file exists purely to satisfy the small interface
 * common/Src/userCan.c and common/f7/Src/userCanF7.c expect from the header
 * named "<BOARD_NAME>_can.h" (pulled in via the AUTOGEN_HEADER_NAME macro in
 * common/Inc/userCan.h), so those shared files can be reused unmodified.
 *
 * Do not wire this up to the DBC generator. HIL's outgoing CAN messages are
 * built by hand in Src/canInject.c to spoof whichever real board's message a
 * given test needs, referencing common/Data/2024CAR.dbc directly for the
 * IDs/signal layout.
 */

#include "stm32f7xx_hal.h"

// HIL is not an addressed node on the vehicle CAN bus.
#define CAN_NODE_ADDRESS 0x00

// common/Src/userCan.c's sendDTCMessage() writes into these before calling
// DTC_SEND_FUNCTION(). HIL never raises DTCs, but the symbols must exist for
// that file to compile.
extern float DTC_Data;
extern float DTC_Severity;
extern float DTC_CODE;

void configCANFilters(CAN_HandleTypeDef *hcan);
HAL_StatusTypeDef init_can_driver(void);
HAL_StatusTypeDef parseCANData(uint32_t id, uint8_t *data);
HAL_StatusTypeDef sendCAN_HIL_DTC(void);

#endif /* HIL_CAN_H */
