/**
  *****************************************************************************
  * @file    mainTaskEntry.c
  * @author  Jacky Lim
  * @brief   Module containing main task, which is the default task for all
  *          boards. It normally blinks the debug LED but the TCU doesn't have
  *          one.
  *****************************************************************************
  */

#include "FreeRTOS.h"
#include "task.h"
#include "bsp.h"
#include "uwfe_debug.h"

#include "lwip.h"

#define MAIN_TASK_PERIOD 1000

extern osThreadId tcpTaskHandle;

void mainTaskFunction(void const * argument)
{
    DEBUG_PRINT("Starting up!!\n");
    TickType_t xLastWakeTime = xTaskGetTickCount();

    MX_LWIP_Init();   /* This function call is autogenerated under the default task.
                       * Meaning I can't move this to the TCP task. See weak version
                       * of mainTaskFunction in freertos.c 
                       */

    xTaskNotify(tcpTaskHandle, 0, eNoAction);   /* Used to unblock tcpTask */

    while (1) {
        vTaskDelayUntil(&xLastWakeTime, MAIN_TASK_PERIOD);
    }
}
