# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(436, 433)
        self.CANSignals = QtWidgets.QTreeWidget(Dialog)
        self.CANSignals.setGeometry(QtCore.QRect(20, 130, 221, 251))
        self.CANSignals.setObjectName("CANSignals")
        self.SelectFile = QtWidgets.QPushButton(Dialog)
        self.SelectFile.setGeometry(QtCore.QRect(140, 90, 105, 32))
        self.SelectFile.setObjectName("SelectFile")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_9.setObjectName("label_9")
        self.FileLocation = QtWidgets.QTextEdit(Dialog)
        self.FileLocation.setGeometry(QtCore.QRect(20, 30, 221, 51))
        self.FileLocation.setObjectName("FileLocation")
        self.GraphBtn = QtWidgets.QPushButton(Dialog)
        self.GraphBtn.setGeometry(QtCore.QRect(310, 390, 113, 32))
        self.GraphBtn.setObjectName("GraphBtn")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(260, 10, 161, 349))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("margin-top: 7px;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setStyleSheet("margin-top:7px")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 2)
        self.DBCFile = QtWidgets.QLineEdit(self.widget)
        self.DBCFile.setStyleSheet("margin-left:25px;\n"
"min-height:20px;")
        self.DBCFile.setObjectName("DBCFile")
        self.gridLayout.addWidget(self.DBCFile, 2, 0, 1, 2)
        self.SelectDBC = QtWidgets.QToolButton(self.widget)
        self.SelectDBC.setObjectName("SelectDBC")
        self.gridLayout.addWidget(self.SelectDBC, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setStyleSheet("margin-top: 7px;\n"
"")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.RegexInput = QtWidgets.QLineEdit(self.widget)
        self.RegexInput.setStyleSheet("margin-left:25px;\n"
"min-height:20px;")
        self.RegexInput.setObjectName("RegexInput")
        self.gridLayout.addWidget(self.RegexInput, 4, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("margin-top: 7px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("margin-left:10px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.MaxXInput = QtWidgets.QLineEdit(self.widget)
        self.MaxXInput.setStyleSheet("min-height:20px;\n"
"")
        self.MaxXInput.setObjectName("MaxXInput")
        self.gridLayout.addWidget(self.MaxXInput, 6, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("margin-left:10px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.MinXInput = QtWidgets.QLineEdit(self.widget)
        self.MinXInput.setStyleSheet("min-height:20px;\n"
"")
        self.MinXInput.setObjectName("MinXInput")
        self.gridLayout.addWidget(self.MinXInput, 7, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("margin-top: 7px;\n"
"")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setStyleSheet("margin-left:10px;\n"
"")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 1)
        self.MaxYInput = QtWidgets.QLineEdit(self.widget)
        self.MaxYInput.setStyleSheet("min-height:20px;\n"
"")
        self.MaxYInput.setObjectName("MaxYInput")
        self.gridLayout.addWidget(self.MaxYInput, 9, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setStyleSheet("margin-left:10px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 0, 1, 1)
        self.MinYInput = QtWidgets.QLineEdit(self.widget)
        self.MinYInput.setStyleSheet("min-height:20px;\n"
"")
        self.MinYInput.setObjectName("MinYInput")
        self.gridLayout.addWidget(self.MinYInput, 10, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CANSignals.headerItem().setText(0, _translate("Dialog", "CAN Signals"))
        self.SelectFile.setText(_translate("Dialog", "Select File"))
        self.label_9.setText(_translate("Dialog", "Current file"))
        self.GraphBtn.setText(_translate("Dialog", "Graph"))
        self.label_2.setText(_translate("Dialog", "Extra Settings"))
        self.label_10.setText(_translate("Dialog", "DBC file:"))
        self.SelectDBC.setText(_translate("Dialog", "..."))
        self.label_8.setText(_translate("Dialog", "Regex:"))
        self.label.setText(_translate("Dialog", "X axis"))
        self.label_3.setText(_translate("Dialog", "Max: "))
        self.label_4.setText(_translate("Dialog", "Min:"))
        self.label_7.setText(_translate("Dialog", "Y axis"))
        self.label_5.setText(_translate("Dialog", "Max: "))
        self.label_6.setText(_translate("Dialog", "Min:"))
