##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.5.0-RC5] date: [Sun Mar 23 13:21:28 EDT 2025] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

THIS_MAKEFILE_PATH := $(CUBE_F7_MAKEFILE_PATH)
######################################
# target
######################################
TARGET = PDU_HIL


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/main.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/gpio.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/freertos.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/can.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/dac.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/i2c.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/tim.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/stm32f7xx_it.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/stm32f7xx_hal_msp.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/stm32f7xx_hal_timebase_tim.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/system_stm32f7xx.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/list.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/queue.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/timers.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1/port.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/sysmem.c \
testbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Src/syscalls.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f769xx.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F769xx


# AS includes
AS_INCLUDES =  \
-ICore/Inc

# C includes
C_INCLUDES =  \
-Itestbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Inc \
-Itestbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Core/Inc \
-Itestbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Inc \
-Itestbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/STM32F7xx_HAL_Driver/Inc/Legacy \
-Itestbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/include \
-Itestbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
-Itestbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
-Itestbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/CMSIS/Device/ST/STM32F7xx/Include \
-Itestbed/HIL_Firmware/pdu_hil/Cube-F7-Src-respin/Drivers/CMSIS/Include \
-Itestbed/HIL_Firmware/pdu_hil/Inc 


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
#CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = $(THIS_MAKEFILE_PATH)/stm32f769bitx_flash.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

