#ifndef PROCESS_CAN_H
#define PROCESS_CAN_H

//Message Definitions
#define PROCESS_RX_TASK_INTERVAL_MS 1
#define BMU_HIL_GPIO_OUTPUTS_MSG 0x401010F
#define BMU_HIL_BATTPOSNEG_MSG 0x402010F
#define BMU_HIL_HVPOSNEGOUTPUT_MSG 0x403010F
#define BMU_HIL_HVSHUNTPOSNEG_MSG 0x404010F

//Signal Startbits
#define BMU_HIL_GPIO_OUTPUTS_CBRB_PRESS 0
#define BMU_HIL_GPIO_OUTPUTS_HVD 1
#define BMU_HIL_GPIO_OUTPUTS_ILCLOSE 2
#define BMU_HIL_GPIO_OUTPUTS_TSMSFAULT 3
#define BMU_HIL_GPIO_OUTPUTS_AMSRESETPRESS 4
#define BMU_HIL_GPIO_OUTPUTS_IMDRESETPRESS 5
#define BMU_HIL_GPIO_OUTPUTS_BPSDRESETPRESS 6
#define BMU_HIL_GPIO_OUTPUTS_IMDFAULT 7
#define BMU_HIL_GPIO_OUTPUTS_IMDSTATUS 8
#define BMU_HIL_GPIO_OUTPUTS_FANTACH 16

#define MASK_12_BIT 0xFFF
#define MASK_13_BIT 0x1FFF


//CAN message IDs

void process_rx_task (void * pvParameters);

#endif/*PROCESS_CAN_H*/