#ifndef PROCESS_CAN_H
#define PROCESS_CAN_H

#define PROCESS_RX_TASK_INTERVAL_MS 1
#define BMU_HIL_GPIO_OUTPUTS_MSG 0x401010F
#define BMU_HIL_BATTPOSNEG_MSG 0x402010F
#define BMU_HIL_HVPOSNEGOUTPUT_MSG 0x403010F
#define BMU_HIL_HVSHUNTPOSNEG_MSG 0x404010F

//CAN message IDs

void process_rx_task (void * pvParameters);

#endif/*PROCESS_CAN_H*/