BUILD_TARGET = HIL
BOARD_NAME = HIL
BOARD_NAME_UPPER = HIL
BOARD_ARCHITECTURE = F7
MCU_DEFINE = STM32F769xx

# HIL is a bench-only CAN test/simulation board - it never ships in the car,
# is not a node in common/Data/2024CAR.dbc, and does not go through the
# DBC/DTC codegen pipeline the vehicle boards use (see README.md for why).
# It still builds through common/tail.mk, the same as every other board
# (same toolchain, same HAL/FreeRTOS glue), and reuses common/'s low-level
# CAN driver to actually put frames on the wire; HIL/Src/HIL_can.c
# hand-implements the small interface common/Src/userCan.c and
# common/f7/Src/userCanF7.c expect, instead of that file being autogenerated
# into a Gen/HIL/ directory.
DBC_CODEGEN = 0

COMMON_LIB_SRC := userCan.c debug.c FreeRTOS_CLI.c freertos_openocd_hack.c newlibHack.c
COMMON_F7_LIB_SRC := userCanF7.c

CUBE_F7_MAKEFILE_PATH := $(BOARD_NAME)/Cube-F7-Src-respin/

include common/tail.mk
