/*
 * userCan.c
 *
 */

#include "userCan.h"
#include "stdbool.h"
#include <string.h>
#include AUTOGEN_HEADER_NAME(BOARD_NAME)
#include "can.h"
#include "debug.h"
#include "bsp.h"
#include "boardTypes.h"
#include "freertos.h"
#include "queue.h"
#include "task.h"

#if IS_BOARD_F7_FAMILY
#include "userCanF7.h"
#elif IS_BOARD_F0_FAMILY
#include "userCanF0.h"
#else
#error no can header file for this board type
#endif


// Call into the autogenerated CAN file to send the DTC message
// Since the autogenerate CAN functions have the board name in them, we need
// this macro to create the right function name for the current board
#define DTC_SEND_FUNCTION CAT(CAT(sendCAN_,BOARD_NAME),_DTC)

volatile bool canStarted = false;

HAL_StatusTypeDef canInit(CAN_HandleTypeDef *hcan)
{
#if IS_BOARD_F7_FAMILY
    if (F7_canInit(hcan) != HAL_OK) {
        return HAL_ERROR;
    }
#elif IS_BOARD_F0_FAMILY
    if (F0_canInit(hcan) != HAL_OK) {
        return HAL_ERROR;
    }
#else
#error canInit not defined for this board type
#endif

    return HAL_OK;
}

HAL_StatusTypeDef canStart(CAN_HandleTypeDef *hcan)
{
    if (!canStarted) {
        canStarted = true;
#if IS_BOARD_F7_FAMILY
        return F7_canStart(hcan);
#elif IS_BOARD_F0_FAMILY
        return F0_canStart(hcan);
#else
#error canStart not defined for this board type
#endif
    } else {
        return HAL_OK;
    }
}

// Are we allowed to send this CAN message now?
// There are 4 priority levels (from high priority (0) to low (3):
// 0: DTC
// 1: Control Messages
// 2: Status Messages
// 3: Debug Messages
// Depending on free mailboxes, can send certain types
HAL_StatusTypeDef canSendCANMessage(uint32_t id, CAN_HandleTypeDef *hcan)
{
    int freeMailboxes = HAL_CAN_GetTxMailboxesFreeLevel(hcan);

    // Look at the priority field of the J1939 style ID
    int priority = (id & 0x1C000000) >> 26;

    if (freeMailboxes == 0) {
        return HAL_ERROR;
    }

    if (freeMailboxes == 1) {
        if (priority == 0 || priority == 1) {
            // Allow high priority messages to send
            return HAL_OK;
        } else {
            DEBUG_PRINT("Blocked msg id %lu, priority %d with free mbx %d\n",
                        id, priority, freeMailboxes);
            return HAL_ERROR;
        }
    } else if (freeMailboxes == 2) {
        if (priority <= 2) {
            return HAL_OK;
        } else {
            DEBUG_PRINT("Blocked msg id %lu, priority %d with free mbx %d\n",
                        id, priority, freeMailboxes);
            return HAL_ERROR;
        }
    } else {
        return HAL_OK;
    }
}

#ifdef CHARGER_CAN_HANDLE
HAL_StatusTypeDef sendCanMessageCharger(uint32_t id, int length, uint8_t *data)
{
    if (!canSendCANMessage(id, &CHARGER_CAN_HANDLE)) {
        return HAL_ERROR;
    }

#if IS_BOARD_F7_FAMILY
    return F7_sendCanMessageCharger(id, length, data);
#else
#error Send can message charger not defined for this board type
#endif
}
#endif

HAL_StatusTypeDef sendCanMessage(uint32_t id, int length, uint8_t *data)
{
    HAL_StatusTypeDef rc;

    if (!canSendCANMessage(id, &CAN_HANDLE)) {
        return HAL_ERROR;
    }

#if IS_BOARD_F7_FAMILY
    rc = F7_sendCanMessage(id, length, data);
#elif IS_BOARD_F0_FAMILY
    rc = F0_sendCanMessage(id, length, data);
#else
#error Send can message not defined for this board type
#endif
    return rc;
}

HAL_StatusTypeDef sendDTCMessage(uint32_t dtcCode, int severity, uint64_t data)
{
    DTC_Data = (float)data;
    DTC_Severity = (float)severity;
    DTC_CODE = (float)dtcCode;
    return DTC_SEND_FUNCTION();
}

/*
 *bool sendCanMessageTimeoutMs(const uint16_t id, const uint8_t *data,
 *                             const uint8_t length, const uint32_t timeout)
 *{
 *    uint32_t beginTime = HAL_GetTick();
 *    bool success = false;
 *    while (HAL_GetTick() < beginTime + timeout && !success)
 *    {
 *        success = sendCanMessage(id, data, length);
 *    }
 *    return success;
 *}
 *
 *bool sendCanMessage(const uint16_t id, const uint8_t *data, const uint8_t length)
 *{
 *    if (length > CAN_MAX_BYTE_LEN)
 *        return false;    // Programmer error
 *    if (initStatus != HAL_OK)
 *        return false;
 *    if (canHandle.Instance->MSR == CAN_MCR_RESET)
 *        return false;
 *
 *    HAL_Delay(1);	// Wait for a previous message to flush out HW
 *
 *    CanTxMsgTypeDef txMessage =
 *    {
 *        .StdId = id,
 *        .IDE = CAN_ID_STD,
 *        .RTR = CAN_RTR_DATA,
 *        .DLC = length
 *    };
 *
 *    uint8_t i;
 *    for (i = 0; i < length; i++)
 *        txMessage.Data[i] = data[i];
 *
 *    canHandle.pTxMsg = &txMessage;
 *    HAL_StatusTypeDef status = HAL_CAN_Transmit_IT(&canHandle);
 *
 *    if (status == HAL_OK)
 *    {
 *        return true;
 *    }
 *    else
 *    {
 *        return false;
 *    }
 *}
 */
