name: Lint Code

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: ["common", "BMU", "PDU", "VCU"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run linter
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            addis0n/arm-none-eabi-gcc-plus-python:wfe2022 \
            bash -c "COMPONENT_LOWER=\$(echo '${{ matrix.component }}' | tr '[:upper:]' '[:lower:]') && \
                     cppcheck --version && \
                     cppcheck --addon=./common/Misra/misra.json --inline-suppr --enable=all -I \${COMPONENT_LOWER}/Inc \${COMPONENT_LOWER}/Src"
